version: '3.8'
services:
  kiosk-frontend:
    build: ./Kios
    image: kiosk-client-image
    container_name: kiosk-client-container
    ports:
      - "6970:6970"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://user:password@db/Greeting"
    
  web-backend:
    build: ./webadmin/Backend
    image: server-image
    container_name: server-container
    ports:
      - "6956:6956"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://user:password@db/Greeting"
  web-frontend:
    build: ./webadmin/Fontend
    image: client-image
    container_name: client-container
    ports:
      - "6958:80"
  db:
    image: mysql:5.7
    container_name: db-container
    ports:
      - "6959:3306"
    environment:
      MYSQL_DATABASE: 'Greeting'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    ports:
      - "6960:80"
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
    depends_on:
      - db
volumes:
  db-data: